CHANGELOG.md, README.md, package.json, src/checkout.ts, src/dintero-checkout-web-sdk.ts, test/dintero-checkout-web-sdk.test.ts
- SessionPaymentOnHold
- SessionPaymentAuthorized
ref: https://github.com/Dintero/checkout-service/issues/1044
=> Support onPayment and SessionPaymentOnHold

CHANGELOG.md, README.md, package-lock.json, package.json
Ref. https://github.com/Dintero/Dintero.Checkout.Web.SDK/pull/4
=> Add version 0.0.13 since wrong build was published to NPM for 0.0.12

package-lock.json
Bump dependencies that has a transitive dependency to
dot-prop
- postcss-calc
- postcss-selector-parser
Fixes: CVE-2020-8116
=> Bump dot-prop from 4.1.1 to 5.2.0

package-lock.json, package.json
Fix transitive dendencies, bump to
- serialize-javascript@4.0.0
- braces@3.0.2
Fixes: WS-2019-0019
Fixes: https://github.com/advisories/GHSA-h9rv-jmmf-4pgx
=> Bump microbundle from 0.11.0 to 0.12.3

README.md, src/checkout.ts, src/index.ts, test/dintero-checkout-web-sdk.test.ts
The `onSessionLocked` handler will now get a callback argument for refreshing the session after a successful update
=> feat(lock): Add callback function to onSessionLocked

.github/workflows/release.yml, package.json
The version number is used in the checkout-url as the query parameter `sdk=x.x.x`, but as the version number is first determined during `semantic-release/npm`, it now says `sdk=0.0.0-development`.
Change the release action to run `npm run build` in the `prepublishOnly` hook, as proposed [here](https://semantic-release.gitbook.io/semantic-release/support/faq#how-can-i-use-a-npm-build-script-that-requires-the-package.jsons-version)
=> fix: Add correct package version to url

CHANGELOG.md, README.md, src/index.ts, test/dintero-checkout-web-sdk.test.ts
-  Changes `lockSession` to return a promise that resolves when the following `SessionLocked` event is returned from the checkout. If a `SessionLockFailed` event is returned from the checkout, the promise is rejected.
-  Changes `refreshSession` to return a promise that resolves when the following `SessionUpdated` event is returned from the checkout. If a `SessionNotFound` event is returned from the checkout, the promise is rejected.
One thing to think about: Maybe the refreshSession event should also fail if the session that was rejected is still locked?
=> feat: Return promise for functions lockSession and refreshSession

src/createIframeAsync.ts
Closes https://github.com/Dintero/checkout/issues/989
Change iframe sandbox properties when embedding checkout so that the walley terms PDF files can be opened.
=> fix: Adds allow-popups-to-escape-sandbox to iframe sandbox

.github/workflows/release.yml, README.md
Pushing tags from shallow clones stopped working at some point. To resolve, use a bigger fetch-depth.
See https://stackoverflow.com/questions/72220249/why-cant-i-push-tags-in-github-workflows-anymore-and-how-do-i-fix-it
=> chore: fix release script by increasing fetch depth

src/checkout.ts, src/index.ts, test/dintero-checkout-web-sdk.test.ts
Adds new internal event "ScrollToTop" so that when the checkout is embedded.
This will allow us to scroll to the top of the iframe before we navigate the user to a 3rd party site.
=> feat: adds scroll to iframe top handler

CHANGELOG.md, src/createIframeAsync.ts
Rel. https://bugs.webkit.org/show_bug.cgi?id=226345
Rel. https://github.com/WebKit/WebKit/pull/11485
Rel. https://webkit.org/blog/14135/release-notes-for-safari-technology-preview-169/
Updates SDK to set the `allow="payment"` property on the iframe so that Apple Pay will work when the checkout is embedded in an iframe.
Verified that the feature woks in the latest Safari Technology Preview by modifying the embedded payment iframe at https://shop.dintero.com
Some RnD is needed to check if this uses the apple pay file located at shop.dintero.com or checkout.dintero.com but that is out of scope for this change.
=> fix: set allow=payment proptery on iframe

src/index.ts
Ref. https://github.com/Dintero/wiki/wiki/incident-reports-2023-08-02-checkout-express-outage
During investigation of the checkout incident I observed that digitroll had a weird singleton to handle double invocations of `onActivePaymentType` when using the SDK. This PR removes the double invocation of the `onActivePaymentType` handler when an event is received by the SDK
=> fix: avoid duplicate invocation of onActivePaymentType

src/popOut.ts, src/url.ts
Ref. https://github.com/Dintero/epics/issues/230
Rel. https://github.com/Dintero/checkout/pull/1170
Fixes logic when checking if the checkout pop out has loaded. When the SDK runtime is on a different origin than the checkout we are noe able to add event listeners to the pop out. Instead we now listen for a message posted by the checkout pop out JS runtime when the checkout application is opened so the SDK can know that the pop out has been loaded successfully.
=> fix: pop out loaded check different origin

package.json
The `postinstall` script fails on hosts that does not have `patch`
installed
Remove the use of `postinstall` to trigger patch of vitest, do the patch
as part of the test script
=> fix(package): install fails because of `postinstall` script

.github/dependabot.yml
Group babel, semantic-release and vitest dev dependencies to reduce the number of PRs
=> chore(dependabot): Change shcedule interval to weekly

LICENSE, package.json
Updates package.json file so that all the typescript declarations are included in the release.
Changes
- Add `files` entry in `package.json`
- Rename file LISENCE → LICENSE and remove trailing spaces
=> fix(build): include ts declarations in release

src/index.ts
Allow modifying the UI mode of checkout when embedding.
Resolves #325
=> feat(embed): add property "ui" to embed options 

.releaserc.json
Ref. https://dintero.slack.com/archives/G7ESUNQ0Z/p1708678043060989
Change configuration for `semantic-release`. With these changes we
- change order of `npm` and `github` plugins (not sure if needed but it matches the order of when they have an effect better)
- add `npm` plugin configuration so that the tarball from `npm pack` is added to the dist folder
- add `github` plugin configuration with an  `asset` entry that takes all tarballs in the dist folder
See related example in the docs for the npm plugin here https://github.com/semantic-release/npm?tab=readme-ov-file#examples
Docs:
- https://github.com/semantic-release/npm
- https://github.com/semantic-release/github
=> fix(build): add asset to github release

.releaserc.json
Fixes https://github.com/Dintero/Dintero.Checkout.Web.SDK/issues/331
Ref. https://github.com/Dintero/Dintero.Checkout.Web.SDK/pull/330
Rel. https://github.com/semantic-release/npm/issues/535
Rel. https://github.com/Dintero/Dintero.Checkout.Web.SDK/actions/runs/8045967660/job/21972265552
The previous config change did not work as intended. The `npm` plugin for semantic release seems to be running twice and the .tgz is not present in the dist folder, and from the logs it does not even look like the package created contains the actual build files either. Instead of trying to make sense of the npm plugin we try using the `exec` plugin to run `npm pack` before the `github` plugin creates is release.
=> fix(build): use exec plugin for github asset

.github/workflows/build.yml, package.json, yarn.lock
Ref. https://github.com/Dintero/Dintero.Checkout.Web.SDK/actions/runs/8061936439
Rel. https://github.com/Dintero/Dintero.Checkout.Web.SDK/pull/332
Rel. https://github.com/Dintero/Dintero.Checkout.Web.SDK/pull/332#pullrequestreview-1902834537
Add new dependency used by build. Also updates build actions from version `@3` to `@4` to handle warnings:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-node@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
=> fix(build): add dev dependency & update build.yml

.github/workflows/release.yml, .releaserc.json
Rel. https://github.com/semantic-release/exec
Ref. https://github.com/Dintero/Dintero.Checkout.Web.SDK/actions/runs/8079360268/job/22073598945
Updates release workflow to also use `actions/checkout@v4` and `actions/setup-node@v4`.
Fixes error in configuration for exec:
> [11:07:25 AM] [semantic-release] › ✔  Completed step "publish" of plugin "@semantic-release/exec"
> [11:07:25 AM] [semantic-release] › ℹ  Start step "publish" of plugin "@semantic-release/github"
🤞 this will finally work.
=> fix(build): exec config uses publishCmd not publish

src/index.ts, src/url.ts, test/dintero-checkout-web-sdk.test.ts, yarn.lock
Add support for new checkout url parameter `"hide_test_message"`, useful for demoing purposes.
Resolves https://github.com/Dintero/Dintero.Checkout.Web.SDK/issues/336
=> feat(embed): Allow hiding test message on creating iframe

.github/workflows/release.yml
To get the aws credentials we need access to create an id-token.
Fixes: #343
=> fix(build): Configure id-token in release build

.github/workflows/build.yml
Github secrets are not visible to pull requests coming from a fork, and in this case dependabot is considered a fork.
As we are not dependent to have the snapshot updated with dependabot's changes, we'll skip these steps for those branches.
Ref: https://github.com/aws-actions/configure-aws-credentials/issues/188#issuecomment-805847804
Ref: https://dintero.slack.com/archives/G7ESUNQ0Z/p1710881795866189
[skip release] as workflow code is not necessary to make a release for
=> chore(build): Skip snapshot CDN upload for dependabot pull requests

src/createIframeAsync.ts
Closes https://github.com/Dintero/Dintero.Checkout.Web.SDK/issues/390
Adds additional sandbox property to iframe.
Verified broken behavior in latest Safari on iPhone in Dintero Demo store when paying via vipps.vipps in embedded iframe. Not sure if vipps started doing something different from before or if a browser update caused this change in behavior.
=> fix(embed): iframe sandbox allow allow-top-navigation

src/createIframeAsync.ts
Ref. https://dintero.slack.com/archives/C077QF56GFR/p1732876810127329?thread_ts=1732201122.662639&cid=C077QF56GFR
Update in functionality in checkout requires extended permissions to work in a cross domain iframe. This pull request adds permission `clipboard-write *` to the `iframe` that embeds the checkout.
https://github.com/user-attachments/assets/6aa5de6b-89a7-42c5-b9b6-a1dfe0a17b5e
=> fix(iframe):Adds cross origin clipboard-write for iframe

.gitignore, package.json, yarn.lock
Updates `webdriverio` from 9.2.1 to 9.4.1
- [Release notes](https://github.com/webdriverio/webdriverio/releases)
- [Changelog](https://github.com/webdriverio/webdriverio/blob/main/CHANGELOG.md)
- [Commits](https://github.com/webdriverio/webdriverio/commits/v9.4.1/packages/webdriverio)
Rel: https://github.com/Dintero/Dintero.Checkout.Web.SDK/pull/428
=> chore(deps-dev): bump webdriverio from 9.2.1 to 9.4.1

.vitest.config.mts, package.json
Remove the extra `--browser.name` and `--browser.headless` arguments
used when running `yarn test`. The browser is now selected from the
`.vitest.config.mts`
> Added `headless` config option to keep the current behaviour, it is
> not needed as `CI=1` will enable it when running test in Github Actions
=> chore(vitest): Enable browser config option

.github/actions/cdn/action.yml
Fix bug, using if directly in steps in composite actions does not work, we have to reference the inputs inside the run instead
With this we will no longer:
- update the latest release with a reference to the dev-assets
- set the dev-build to latest in the assets
=> chore(build): Skip updating github-release for dev build

.github/workflows/release.yml
#487 fixed the bug of updating github releases and latest when running the pull request build. There is however, still an issue when merging a pull request and it doesn't lead to a new version will update the latest github release and upload the version to latest in the CDN, which we don't want.
Attempting to fix this by adding a conditional
=> chore(build): Skip updating github-release when no new release

.gitignore, src/popOut.ts
Avoid `window is not defined` err in SSR context
Resolves https://github.com/Dintero/Dintero.Checkout.Web.SDK/issues/514
=> fix(popOut): move width, height const to initializer 
